const KittensActionTypes = {
  REQUEST_KITTENS_PENDING: "REQUEST_KITTENS_PENDING ",
  REQUEST_KITTENS_SUCCESS: "REQUEST_KITTENS_SUCCESS ",
  REQUEST_KITTENS_FAILED: "REQUEST_KITTENS_FAILED "
};

export default KittensActionTypes;
